
name: CI
on:
  push:
    branches: [master, main]
  pull_request:
jobs:
  test:
    name: ${{ matrix.command }} ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [openjdk@1.11.0, openjdk@1.17.0]
        command:
          - "test"
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - run: sbt ${{ matrix.command }}
