
name: Build and Deploy GhPages docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt          

      - name: Build
        run: sbt "hepekDocs/hepek"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: hepek-docs/hepek_output
